# @package _global_
estimator_type: MixtureDensityNetworkEstimator

# Estimating model specific params
estimator:
  _target_: rfi.backend.mdn.${estimator_type}
  fit_method: fit
  fit_params:
    weight_decay: 0.0001
    time_budget_s:
  sampler:
    _target_: rfi.samplers.mdn.MDNSampler