# @package _global_
estimator_type: MixtureDensityNetworkEstimator

# Estimating model specific params
estimator:
  _target_: rfi.backend.mdn.${estimator_type}
  fit_method: fit
  fit_params:
    n_components: 4
    time_budget_s:
    verbose: True
    weight_decay: 0.05
    batch_size:
    num_cpus: 13
  sampler:
    _target_: rfi.samplers.mdn.MDNSampler