# @package _global_
estimator_type: NormalisingFlowEstimator

# Estimating model specific params
estimator:
  _target_: rfi.backend.cnf.${estimator_type}
  fit_method: fit
  restrict_support: False
  fit_params:
    time_budget_s:
    verbose: True
    inputs_normalization: True
    batch_size:
  sampler:
    _target_: rfi.samplers.cnflow.CNFSampler


data:
  normalise_params:
    with_mean: True