# @package _global_
estimator_type: NormalisingFlowEstimator

# Estimating model specific params
estimator:
  _target_: rfi.backend.cnf.${estimator_type}
  fit_method: fit
  fit_params:
    time_budget_s:
    verbose: True
  sampler:
    _target_: rfi.samplers.cnflow.CNFSampler