# @package _global_
sem_type: RandomGPGaussianNoiseSEM

# SEM specific params
data_generator:
  sem_type: ${sem_type}
  sem:
    interpolation_switch: ${data.n_train}
    default_noise_std_bounds: [0.63245553203, 0.894427191]
