# Data generating mechanism setup
data_generator:
  dag:
    n: 6
    p: 0.2
    seed: 42
  sem_type: ???
  sem:
    _target_: rfi.backend.causality.${data_generator.sem_type}
    seed: 42

# Data sampling details
data:
  n_train: 1000
  train_seed: 42
  n_test: 100
  test_seed: 4242

# Conditional density estimator
estimator:
  _target_: ???
  fit_method: ???
  fit_params:
  sampler: ???

# Predictive model for RFI
pred_model:
  _target_: sklearn.linear_model.LinearRegression


# Experiment parameters
exp:
  check_exisisting_hash: True
  conditioning_mode: all  # true_parents, true_markov_blanket, all
  mlflow_uri: http://127.0.0.1:5000
  metrics:
    epsabs: 0.01
  mb_dist:
    method: mc  # quad, mc
    quad_epsabs: 0.001
    mc_size: 5000
  rfi:
    risk: mean_squared_error
    nr_runs: 50



defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

