# Dataset details
data:
  relative_path: ???
  sample_ind: 1  # For sachs_2005 - 1, for syntren - 1...10
  test_ratio: 0.2
  split_seed: 42

# Conditional density estimator
estimator:
  _target_: ???
  fit_method: ???
  fit_params:
  sampler: ???

# Predictive model for RFI
pred_model:
  _target_: sklearn.linear_model.LinearRegression


# Experiment parameters
exp:
  mlflow_uri: http://127.0.0.1:5000
  rfi:
    risk: mean_squared_error
    nr_runs: 50


defaults:
  - hydra/job_logging: colorlog
  - hydra/hydra_logging: colorlog

